spring.application.name=backend

server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authserver:9000/oauth2/jwks
spring.security.oauth2.resourceserver.jwt.audiences=angular-client

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
kafka.groups.business-profile=${KAFKA_GROUP_BUSINESS_PROFILE:business-profile-group}
kafka.groups.resource-promotion=${KAFKA_GROUP_RESOURCE_PROMOTION:resource-promotion-group}


